
export const SHOW_TEXT = "SHOW_TEXT";
export const DISPLAY_SIGN_UP_MODAL = "DISPLAY_SIGN_UP_MODAL";
export const DISPLAY_SIGN_IN_MODAL = "DISPLAY_SIGN_IN_MODAL";
export const SUBMIT_SEARCH_FIELD = "SUBMIT_SEARCH_FIELD";