
export const SHOW_TEXT = "SHOW_TEXT";
export const DISPLAY_SIGN_UP_MODAL = "DISPLAY_SIGN_UP_MODAL";
export const DISPLAY_LOG_IN_MODAL = "DISPLAY_LOG_IN_MODAL";
export const SUBMIT_SEARCH_FIELD = "SUBMIT_SEARCH_FIELD";
export const SUBMIT_EMAIL = "SUBMIT_EMAIL";
export const SUBMIT_CRYPTED_PASSWORD = "SUBMIT_CRYPTED_PASSWORD";
